# Generated by Django 5.1.4 on 2025-01-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='data_de_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='foto',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
