# Generated by Django 5.1.4 on 2025-01-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_amigo_bio_alter_amigo_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amizade',
            old_name='destinatário',
            new_name='destinatario',
        ),
    ]
