# Generated by Django 5.1.5 on 2025-02-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_destinatário_amizade_destinatario"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Sugestao",
        ),
        migrations.RenameField(
            model_name="sugestao",
            old_name="Amigo",
            new_name="amigo",
        ),
    ]
